name: azercell_task_application
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  # state management
  flutter_bloc: ^8.0.0
  equatable: ^2.0.5
  # stream controller
  rxdart: ^0.27.0
  # dependency injection
  get_it: ^7.1.3
  #validator
  reactive_forms: ^16.1.1
  
  cupertino_icons: ^1.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

